name: Build with PlatformIO for ESP32

on:
  push:
    branches:
      - main

env:
  PLATFORMIO_CI_SRC: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Compile code
      run: |
           export GIT_IDENT=$(git rev-parse --short HEAD)
           platformio project init
           pio run
           # pio run -v -t upload || true # Show all firmware parts and commands
           mkdir -p firmware/esp8266/
           cp .pio/build/wemos_mini/firmware.bin firmware/esp8266/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: firmware/
